### PR TITLE
feat: make it possible to generate multiple multiqc reports using the same rule

### PR DESCRIPTION
**Pull request by Smeds**

### CODE REVIEW

**Comment by Smeds** [comment]
Talked with Jonas about multiqc and the question is if we should update the wrapper or alternativ don't use it. Now it will search throught all directories of the provided files when it would be better if it just used the files we inpute to the rule. With the current implementation, more files then the those we provide could be included in the report.

**Comment by marrip** [comment]
Oh, and we cannot configure the wrapper to limit it to the input files? Maybe it would be better to omit the wrapper then. 😬 Or if you feel generous to put a PR for the wrapper.

**Comment by Smeds** [comment]
> Oh, and we cannot configure the wrapper to limit it to the input files? Maybe it would be better to omit the wrapper then. grimacing Or if you feel generous to put a PR for the wrapper.

I could do both! At the moment it takes a long time to have pull-request reviewed at the different snakemake repos.

**Comment by marrip** [comment]
> > Oh, and we cannot configure the wrapper to limit it to the input files? Maybe it would be better to omit the wrapper then. grimacing Or if you feel generous to put a PR for the wrapper.
> 
> I could do both! At the moment it takes a long time to have pull-request reviewed at the different snakemake repos.

Let's omit it then 😃

**Comment by Smeds** [comment]
> > > Oh, and we cannot configure the wrapper to limit it to the input files? Maybe it would be better to omit the wrapper then. grimacing Or if you feel generous to put a PR for the wrapper.
> > 
> > 
> > I could do both! At the moment it takes a long time to have pull-request reviewed at the different snakemake repos.
> 
> Let's omit it then smiley

The rule will no use shell instead of a wrapper. And a pull-request against the wrapper repo is waiting for approval.

**Pull request merged**
